@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.user.token}}

### Register user 
# @name register

POST  {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Felhasznalo 1",
    "address": "6500, idenegyere utca, 2",
    "email": "felhasznalo@gmail.com",
    "password": "Felhasznalo123"
}

### login user
# @name login

POST  {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "kevin@turr.hu",
    "password": "Turr123"
}

### upload ad
# @name upload

POST  {{baseUrl}}/ads/upload
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "date": "2025-02-12",
    "category": "Videó játék",
    "title": "Fortnite3",
    "description": "ingyenes de eladom",
    "price": 2000,
    "userId":"185989f3-e050-4ae8-91e4-ea0b200863ba"
}

### delete ad
# @name delete

DELETE  {{baseUrl}}/ads/delete/92e8b8c0-5d72-447f-8f55-9a314aa3f6e8
Content-Type: application/json
Authorization: Bearer {{authToken}}

### get all ad
# @name getAll

GET {{baseUrl}}/ads/get
Authorization: Bearer {{authToken}}

### get ad by id
# @name getOneById

GET {{baseUrl}}/ads/get/4d6b4c3d-542d-4e9a-8ea4-51ee0cf5cce0
Content-Type: application/json
Authorization: Bearer {{authToken}}